<meta charset="<?= $_charset; ?>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= $_title; ?></title>
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->


<?php if ($_controller == "pages" && $_action == "welcome"): ?>
    <link rel="stylesheet" href="<?= $_css("home"); ?>"/>
<?php else: ?>
    <link rel="stylesheet" href="<?= $_css("style"); ?>"/>
<?php endif; ?>
    
