<h1>Adicionar pessoa a uma ocupação</h1>
<div>
    <form action="<?= $_refer("usuarios/add"); ?>" method="post">
        <label>Escreva seu username</label><br>
        <input type='text' name='username' required="true" placeholder="Escreva seu username"><br>
        <label>Escreva a sua email</label><br>
        <input type='text' name='email' required="true" placeholder="Escreva a sua email"><br>
        <label>Escreva o seu CPF</label><br>
        <input type='text' name='CPF' required="true" placeholder="Escreva o seu CPF"><br>
        <label>Escreva o seu Senha</label><br>
        <input type='password' name='password' required="true" placeholder="Escreva o sua Senha"><br>
        <label>Escreva o sua permissão</label><br>
        <input type='text' name='allow' required="true" placeholder="Escreva o sua Permissão"><br>
        <input type="submit" value="salvar">
    </form>
</div>


<!--<h1>Adicionar pessoa a uma ocupação</h1>
<div>
    <form action="<?= $_refer("ocupacoes/add"); ?>" method="post">
        <label>Escreva seu nome</label><br>
        <input type='text' name='name' required="true" placeholder="Escreva seu nome"><br>
        <label>Escreva a sua ocupação</label><br>
        <input type='text' name='occupation' required="true" placeholder="Escreva a sua ocupação"><br>
        <label>Escreva o seu email</label><br>
        <input type='text' name='email' required="true" placeholder="Escreva o seu email"><br>
        <input type="submit" value="salvar">
    </form>
</div>