<?php if ($_allows("view")): ?>
    <h1>Minha lista de úsuarios</h1>

    <div>
        <?php if ($_allows("add")): ?><a href="<?= $_refer("usuario/add"); ?>">Novo registro</a><?php endif; ?> | <a href="<?= $_refer("logout"); ?>">Sair</a>
    </div>

    <table>
        <tr>
            <th>#</th>
            <th>Data de Criação</th>
            <th>Data de Atualização</th>
            <th>Nome</th>
            <th>Email</th>
            <th>CPF</th>
            <th>Permissão</th>
            <th>Opções</th>
        </tr>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?= $user["id"]; ?></td>
                <td><?= $user["created"]; ?></td>
                <td><?= $user["updated"]; ?></td>
                <td><?= $user["username"]; ?></td>
                <td><?= $user["email"]; ?></td>
                <td><?= $user["cpf"]; ?></td>
                <td><?= $user["allow"]; ?></td>
                <td>
                    <?php if ($_allows("edit")): ?>
                        <a href="<?= $_refer("usuarios/edit/" . $user["id"]); ?>">Atualizar</a>
                    <?php endif; ?>
                    <?php if ($_allows("delete")): ?>
                        <a href="<?= $_refer("usuarios/delete/" . $user["id"]); ?>">Excluir</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>