<h1>Lista de Contatos</h1>

<form method="post" action="<?= $_refer("solicitacoes/index/1/100/asc"); ?>">
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" name="nome" id="nome" class="form-control" required="true">
        <div id="emailHelp" class="form-text">Digite seu nome.</div>
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" name="email" id="email" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">E-mail</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td><?= $users["nome"]; ?></td>
            <td><?= $users["email"]; ?></td>
        </tr>
    </tbody>
</table>