<div class="container error-page d-flex flex-wrap m-auto">
    <div class="row">
        <div class="col pt-5 m-auto text-center">
            <div class="col">
                <h1>Erro no Servidor!</h1>
            </div>
            <h4>O que fazer?</h4>
            <p>O site encontrou um erro ao recuperar esta página. Recarregue essa página mais tarde ou acesse:
                <br>
                <br>
                <a class="nav-link fw-bold d-inline <?= $act_home; ?>" href="<?= $_refer(); ?>"> <i class="bi bi-house-fill"></i> Início </a>
                <a class="nav-link fw-bold d-inline mx-3 <?= $act_menu; ?>" href="<?= $_refer("dashboard"); ?>"> <i class="bi bi-menu-button-wide-fill"></i> Menu </a>
                <a class="nav-link fw-bold d-inline" href="javascript:history.back()">
                    <i class="bi bi-arrow-left-circle-fill"></i> Voltar
                </a>
            </p>
        </div>
        <div class="col text-center">
            <img src="<?= $_img("500.svg"); ?>">
        </div>
    </div>
</div>