<header>
    <h1>Agenda de Digital</h1>
</header>

<div>

    <h2>Login</h2>
    <form action="<?= $_refer("contatos"); ?>" method="post">
        <input type="email" name="usuario" id="usuario" placeholder="Usuário" autocomplete="on" required autofocus>
        <br>
        <input type="text" name="senha" id="senha" placeholder="Senha" required>
        <br>
        <input type="submit" value="Entrar" >
    </form>
</div>