<form class="form-box" method="POST" action="<?= $_refer("users/add"); ?>">
    <div class="container">
        <div class=" card col-12 my-5 m-auto" style="width: 120vh;">
            <div class="card-body">
                <h1>Criar novo usuário</h1>
                <hr>
                <div class="row">
                    <div class="col-sm-6 my-5">
                        <div class="card">
                            <div class="card-header">
                                <?php if ($error) : ?>
                                    <div class="alert alert-danger"><?= $error; ?></div>
                                <?php endif; ?>
                                <h1 class="d-flex justify-content-center">Dados</h2>
                            </div>
                            <div class="card-body">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="name" id="floatingName" placeholder="Nome completo" required="true" value="<?= $name; ?>">
                                    <label for="floatingName">Nome completo:</label>
                                </div>
                                <hr>
                                <div class="form-floating mb-3">
                                    <input type="email" class="form-control" name="email" id="floatingEmail" placeholder="E-mail" required="true" value="<?= $email; ?>">
                                    <label for="floatingEmail">E-mail:</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <input type="tel" class="form-control tel" name="tel" id="floatingTel" placeholder="Telefone" required="true" value="<?= $tel; ?>">
                                    <label for="floatingTel">Telefone:</label>
                                </div>
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" name="registration" id="floatingEmail" placeholder="Matrícula" required="true" value="<?= $registration; ?>">
                                    <label for="floatingEmail">Matrícula:</label>
                                </div>
                                <div class="ajax_users_department_distinct_all" data-refer="<?= $_refer("users/ajax_users_department_distinct_all") ?>" data-value="<?= $department; ?>"></div>
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="floatingReferPassword" placeholder="Senha padrão" disabled="" value="sutin">
                                    <label for="floatingReferPassword">Senha padrão:</label>
                                </div>
                                <div class="card-body">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 my-5">
                        <div class="card">
                            <div class="card-header">
                                <?php if ($error) : ?>
                                    <div class="alert alert-danger"><?= $error; ?></div>
                                <?php endif; ?>
                                <h1 class="d-flex justify-content-center">Permissões</h2>
                            </div>
                            <div class="card-body">
                                <?php include $_element("parts/allows"); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-center form-floating mb-3">
                    <input type="submit" class="btn effect-positive" value="Cadastrar Usuário">
                </div>
            </div>
        </div>
    </div>
</form>